version: '3'

services:
  hugo:
    image: jakejarvis/hugo-extended:latest
    volumes:
      - ./:/src
    command: --watch

# Use nginx to serve the generated files
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html